#!/usr/bin/env bash

# Theme Definitions for GeminiSH

# --- Light Theme ---
THEME_LIGHT_BACKGROUND="#FFFFFF"
THEME_LIGHT_FOREGROUND="#000000"
THEME_LIGHT_PRIMARY="#0D6EFD" # Blue
THEME_LIGHT_SECONDARY="#6C757D" # Gray
THEME_LIGHT_SUCCESS="#198754" # Green
THEME_LIGHT_DANGER="#DC3545" # Red
THEME_LIGHT_WARNING="#FFC107" # Yellow
THEME_LIGHT_INFO="#0DCAF0" # Cyan
THEME_LIGHT_HEADER="#E40406" # Red (keeping original header color for now)
THEME_LIGHT_SPINNER="#0D6EFD"
THEME_LIGHT_ERROR_BACKGROUND="#F8D7DA"
THEME_LIGHT_ITEM="#343A40"
THEME_LIGHT_SELECTED_ITEM="#0D6EFD"


# --- Dark Theme ---
THEME_DARK_BACKGROUND="#212529"
THEME_DARK_FOREGROUND="#F8F9FA"
THEME_DARK_PRIMARY="#0D6EFD" # Blue
THEME_DARK_SECONDARY="#6C757D" # Gray
THEME_DARK_SUCCESS="#198754" # Green
THEME_DARK_DANGER="#DC3545" # Red
THEME_DARK_WARNING="#FFC107" # Yellow
THEME_DARK_INFO="#0DCAF0" # Cyan
THEME_DARK_HEADER="#E40406" # Red
THEME_DARK_SPINNER="#0D6EFD"
THEME_DARK_ERROR_BACKGROUND="#3A1E21"
THEME_DARK_ITEM="#ADB5BD"
THEME_DARK_SELECTED_ITEM="#0D6EFD"


# --- Dracula Theme ---
# Official Dracula colors: https://spec.draculatheme.com/
THEME_DRACULA_BACKGROUND="#282A36"
THEME_DRACULA_CURRENT_LINE="#44475A"
THEME_DRACULA_FOREGROUND="#F8F8F2"
THEME_DRACULA_COMMENT="#6272A4"
THEME_DRACULA_CYAN="#8BE9FD"
THEME_DRACULA_GREEN="#50FA7B"
THEME_DRACULA_ORANGE="#FFB86C"
THEME_DRACULA_PINK="#FF79C6"
THEME_DRACULA_PURPLE="#BD93F9"
THEME_DRACULA_RED="#FF5555"
THEME_DRACULA_YELLOW="#F1FA8C"
# Mapping to our categories
THEME_DRACULA_PRIMARY="${THEME_DRACULA_PURPLE}"
THEME_DRACULA_SECONDARY="${THEME_DRACULA_COMMENT}"
THEME_DRACULA_SUCCESS="${THEME_DRACULA_GREEN}"
THEME_DRACULA_DANGER="${THEME_DRACULA_RED}"
THEME_DRACULA_WARNING="${THEME_DRACULA_ORANGE}"
THEME_DRACULA_INFO="${THEME_DRACULA_CYAN}"
THEME_DRACULA_HEADER="${THEME_DRACULA_PINK}"
THEME_DRACULA_SPINNER="${THEME_DRACULA_PINK}"
THEME_DRACULA_ERROR_BACKGROUND="#44475A" # Current Line as background for error block
THEME_DRACULA_ITEM="${THEME_DRACULA_FOREGROUND}"
THEME_DRACULA_SELECTED_ITEM="${THEME_DRACULA_PINK}"


# --- Catppuccin Latte ---
THEME_CATPPUCCIN_LATTE_ROSEWATER="#dc8a78"
THEME_CATPPUCCIN_LATTE_FLAMINGO="#dd7878"
THEME_CATPPUCCIN_LATTE_PINK="#ea76cb"
THEME_CATPPUCCIN_LATTE_MAUVE="#8839ef"
THEME_CATPPUCCIN_LATTE_RED="#d20f39"
THEME_CATPPUCCIN_LATTE_MAROON="#e64553"
THEME_CATPPUCCIN_LATTE_PEACH="#fe640b"
THEME_CATPPUCCIN_LATTE_YELLOW="#df8e1d"
THEME_CATPPUCCIN_LATTE_GREEN="#40a02b"
THEME_CATPPUCCIN_LATTE_TEAL="#179299"
THEME_CATPPUCCIN_LATTE_SKY="#04a5e5"
THEME_CATPPUCCIN_LATTE_SAPPHIRE="#209fb5"
THEME_CATPPUCCIN_LATTE_BLUE="#1e66f5"
THEME_CATPPUCCIN_LATTE_LAVENDER="#7287fd"
THEME_CATPPUCCIN_LATTE_TEXT="#4c4f69"
THEME_CATPPUCCIN_LATTE_SUBTEXT1="#5c5f77"
THEME_CATPPUCCIN_LATTE_SUBTEXT0="#6c6f85"
THEME_CATPPUCCIN_LATTE_OVERLAY2="#7c7f93"
THEME_CATPPUCCIN_LATTE_OVERLAY1="#8c8fa1"
THEME_CATPPUCCIN_LATTE_OVERLAY0="#9ca0b0"
THEME_CATPPUCCIN_LATTE_SURFACE2="#acb0be"
THEME_CATPPUCCIN_LATTE_SURFACE1="#bcc0cc"
THEME_CATPPUCCIN_LATTE_SURFACE0="#ccd0da"
THEME_CATPPUCCIN_LATTE_BASE="#eff1f5"
THEME_CATPPUCCIN_LATTE_MANTLE="#e6e9ef"
THEME_CATPPUCCIN_LATTE_CRUST="#dce0e8"
# Mapping
THEME_CATPPUCCIN_LATTE_BACKGROUND="${THEME_CATPPUCCIN_LATTE_BASE}"
THEME_CATPPUCCIN_LATTE_FOREGROUND="${THEME_CATPPUCCIN_LATTE_TEXT}"
THEME_CATPPUCCIN_LATTE_PRIMARY="${THEME_CATPPUCCIN_LATTE_BLUE}"
THEME_CATPPUCCIN_LATTE_SECONDARY="${THEME_CATPPUCCIN_LATTE_LAVENDER}"
THEME_CATPPUCCIN_LATTE_SUCCESS="${THEME_CATPPUCCIN_LATTE_GREEN}"
THEME_CATPPUCCIN_LATTE_DANGER="${THEME_CATPPUCCIN_LATTE_RED}"
THEME_CATPPUCCIN_LATTE_WARNING="${THEME_CATPPUCCIN_LATTE_YELLOW}"
THEME_CATPPUCCIN_LATTE_INFO="${THEME_CATPPUCCIN_LATTE_TEAL}"
THEME_CATPPUCCIN_LATTE_HEADER="${THEME_CATPPUCCIN_LATTE_MAUVE}"
THEME_CATPPUCCIN_LATTE_SPINNER="${THEME_CATPPUCCIN_LATTE_PINK}"
THEME_CATPPUCCIN_LATTE_ERROR_BACKGROUND="${THEME_CATPPUCCIN_LATTE_MAROON}" # Maroon as background for error, text should be light
THEME_CATPPUCCIN_LATTE_ITEM="${THEME_CATPPUCCIN_LATTE_TEXT}"
THEME_CATPPUCCIN_LATTE_SELECTED_ITEM="${THEME_CATPPUCCIN_LATTE_PINK}"


# --- Catppuccin Frappe ---
THEME_CATPPUCCIN_FRAPPE_ROSEWATER="#f2d5cf"
THEME_CATPPUCCIN_FRAPPE_FLAMINGO="#eebebe"
THEME_CATPPUCCIN_FRAPPE_PINK="#f4b8e4"
THEME_CATPPUCCIN_FRAPPE_MAUVE="#ca9ee6"
THEME_CATPPUCCIN_FRAPPE_RED="#e78284"
THEME_CATPPUCCIN_FRAPPE_MAROON="#ea999c"
THEME_CATPPUCCIN_FRAPPE_PEACH="#ef9f76"
THEME_CATPPUCCIN_FRAPPE_YELLOW="#e5c890"
THEME_CATPPUCCIN_FRAPPE_GREEN="#a6d189"
THEME_CATPPUCCIN_FRAPPE_TEAL="#81c8be"
THEME_CATPPUCCIN_FRAPPE_SKY="#99d1db"
THEME_CATPPUCCIN_FRAPPE_SAPPHIRE="#85c1dc"
THEME_CATPPUCCIN_FRAPPE_BLUE="#8caaee"
THEME_CATPPUCCIN_FRAPPE_LAVENDER="#babbf1"
THEME_CATPPUCCIN_FRAPPE_TEXT="#c6d0f5"
THEME_CATPPUCCIN_FRAPPE_SUBTEXT1="#b5bfe2"
THEME_CATPPUCCIN_FRAPPE_SUBTEXT0="#a5adce"
THEME_CATPPUCCIN_FRAPPE_OVERLAY2="#949cbb"
THEME_CATPPUCCIN_FRAPPE_OVERLAY1="#838ba7"
THEME_CATPPUCCIN_FRAPPE_OVERLAY0="#737994"
THEME_CATPPUCCIN_FRAPPE_SURFACE2="#626880"
THEME_CATPPUCCIN_FRAPPE_SURFACE1="#51576d"
THEME_CATPPUCCIN_FRAPPE_SURFACE0="#414559"
THEME_CATPPUCCIN_FRAPPE_BASE="#303446"
THEME_CATPPUCCIN_FRAPPE_MANTLE="#292c3c"
THEME_CATPPUCCIN_FRAPPE_CRUST="#232634"
# Mapping
THEME_CATPPUCCIN_FRAPPE_BACKGROUND="${THEME_CATPPUCCIN_FRAPPE_BASE}"
THEME_CATPPUCCIN_FRAPPE_FOREGROUND="${THEME_CATPPUCCIN_FRAPPE_TEXT}"
THEME_CATPPUCCIN_FRAPPE_PRIMARY="${THEME_CATPPUCCIN_FRAPPE_BLUE}"
THEME_CATPPUCCIN_FRAPPE_SECONDARY="${THEME_CATPPUCCIN_FRAPPE_LAVENDER}"
THEME_CATPPUCCIN_FRAPPE_SUCCESS="${THEME_CATPPUCCIN_FRAPPE_GREEN}"
THEME_CATPPUCCIN_FRAPPE_DANGER="${THEME_CATPPUCCIN_FRAPPE_RED}"
THEME_CATPPUCCIN_FRAPPE_WARNING="${THEME_CATPPUCCIN_FRAPPE_YELLOW}"
THEME_CATPPUCCIN_FRAPPE_INFO="${THEME_CATPPUCCIN_FRAPPE_TEAL}"
THEME_CATPPUCCIN_FRAPPE_HEADER="${THEME_CATPPUCCIN_FRAPPE_MAUVE}"
THEME_CATPPUCCIN_FRAPPE_SPINNER="${THEME_CATPPUCCIN_FRAPPE_PINK}"
THEME_CATPPUCCIN_FRAPPE_ERROR_BACKGROUND="${THEME_CATPPUCCIN_FRAPPE_SURFACE0}"
THEME_CATPPUCCIN_FRAPPE_ITEM="${THEME_CATPPUCCIN_FRAPPE_TEXT}"
THEME_CATPPUCCIN_FRAPPE_SELECTED_ITEM="${THEME_CATPPUCCIN_FRAPPE_PINK}"


# --- Catppuccin Macchiato ---
THEME_CATPPUCCIN_MACCHIATO_ROSEWATER="#f4dbd6"
THEME_CATPPUCCIN_MACCHIATO_FLAMINGO="#f0c6c6"
THEME_CATPPUCCIN_MACCHIATO_PINK="#f5bde6"
THEME_CATPPUCCIN_MACCHIATO_MAUVE="#c6a0f6"
THEME_CATPPUCCIN_MACCHIATO_RED="#ed8796"
THEME_CATPPUCCIN_MACCHIATO_MAROON="#ee99a0"
THEME_CATPPUCCIN_MACCHIATO_PEACH="#f5a97f"
THEME_CATPPUCCIN_MACCHIATO_YELLOW="#eed49f"
THEME_CATPPUCCIN_MACCHIATO_GREEN="#a6da95"
THEME_CATPPUCCIN_MACCHIATO_TEAL="#8bd5ca"
THEME_CATPPUCCIN_MACCHIATO_SKY="#91d7e3"
THEME_CATPPUCCIN_MACCHIATO_SAPPHIRE="#7dc4e4"
THEME_CATPPUCCIN_MACCHIATO_BLUE="#8aadf4"
THEME_CATPPUCCIN_MACCHIATO_LAVENDER="#b7bdf8"
THEME_CATPPUCCIN_MACCHIATO_TEXT="#cad3f5"
THEME_CATPPUCCIN_MACCHIATO_SUBTEXT1="#b8c0e0"
THEME_CATPPUCCIN_MACCHIATO_SUBTEXT0="#a5adce"
THEME_CATPPUCCIN_MACCHIATO_OVERLAY2="#939ab7"
THEME_CATPPUCCIN_MACCHIATO_OVERLAY1="#8087a2"
THEME_CATPPUCCIN_MACCHIATO_OVERLAY0="#6e738d"
THEME_CATPPUCCIN_MACCHIATO_SURFACE2="#5b6078"
THEME_CATPPUCCIN_MACCHIATO_SURFACE1="#494d64"
THEME_CATPPUCCIN_MACCHIATO_SURFACE0="#363a4f"
THEME_CATPPUCCIN_MACCHIATO_BASE="#24273a"
THEME_CATPPUCCIN_MACCHIATO_MANTLE="#1e2030"
THEME_CATPPUCCIN_MACCHIATO_CRUST="#181926"
# Mapping
THEME_CATPPUCCIN_MACCHIATO_BACKGROUND="${THEME_CATPPUCCIN_MACCHIATO_BASE}"
THEME_CATPPUCCIN_MACCHIATO_FOREGROUND="${THEME_CATPPUCCIN_MACCHIATO_TEXT}"
THEME_CATPPUCCIN_MACCHIATO_PRIMARY="${THEME_CATPPUCCIN_MACCHIATO_BLUE}"
THEME_CATPPUCCIN_MACCHIATO_SECONDARY="${THEME_CATPPUCCIN_MACCHIATO_LAVENDER}"
THEME_CATPPUCCIN_MACCHIATO_SUCCESS="${THEME_CATPPUCCIN_MACCHIATO_GREEN}"
THEME_CATPPUCCIN_MACCHIATO_DANGER="${THEME_CATPPUCCIN_MACCHIATO_RED}"
THEME_CATPPUCCIN_MACCHIATO_WARNING="${THEME_CATPPUCCIN_MACCHIATO_YELLOW}"
THEME_CATPPUCCIN_MACCHIATO_INFO="${THEME_CATPPUCCIN_MACCHIATO_TEAL}"
THEME_CATPPUCCIN_MACCHIATO_HEADER="${THEME_CATPPUCCIN_MACCHIATO_MAUVE}"
THEME_CATPPUCCIN_MACCHIATO_SPINNER="${THEME_CATPPUCCIN_MACCHIATO_PINK}"
THEME_CATPPUCCIN_MACCHIATO_ERROR_BACKGROUND="${THEME_CATPPUCCIN_MACCHIATO_SURFACE0}"
THEME_CATPPUCCIN_MACCHIATO_ITEM="${THEME_CATPPUCCIN_MACCHIATO_TEXT}"
THEME_CATPPUCCIN_MACCHIATO_SELECTED_ITEM="${THEME_CATPPUCCIN_MACCHIATO_PINK}"


# --- Catppuccin Mocha ---
THEME_CATPPUCCIN_MOCHA_ROSEWATER="#f5e0dc"
THEME_CATPPUCCIN_MOCHA_FLAMINGO="#f2cdcd"
THEME_CATPPUCCIN_MOCHA_PINK="#f5c2e7"
THEME_CATPPUCCIN_MOCHA_MAUVE="#cba6f7"
THEME_CATPPUCCIN_MOCHA_RED="#f38ba8"
THEME_CATPPUCCIN_MOCHA_MAROON="#eba0ac"
THEME_CATPPUCCIN_MOCHA_PEACH="#fab387"
THEME_CATPPUCCIN_MOCHA_YELLOW="#f9e2af"
THEME_CATPPUCCIN_MOCHA_GREEN="#a6e3a1"
THEME_CATPPUCCIN_MOCHA_TEAL="#94e2d5"
THEME_CATPPUCCIN_MOCHA_SKY="#89dceb"
THEME_CATPPUCCIN_MOCHA_SAPPHIRE="#74c7ec"
THEME_CATPPUCCIN_MOCHA_BLUE="#89b4fa"
THEME_CATPPUCCIN_MOCHA_LAVENDER="#b4befe"
THEME_CATPPUCCIN_MOCHA_TEXT="#cdd6f4"
THEME_CATPPUCCIN_MOCHA_SUBTEXT1="#bac2de"
THEME_CATPPUCCIN_MOCHA_SUBTEXT0="#a6adc8"
THEME_CATPPUCCIN_MOCHA_OVERLAY2="#9399b2"
THEME_CATPPUCCIN_MOCHA_OVERLAY1="#7f849c"
THEME_CATPPUCCIN_MOCHA_OVERLAY0="#6c7086"
THEME_CATPPUCCIN_MOCHA_SURFACE2="#585b70"
THEME_CATPPUCCIN_MOCHA_SURFACE1="#45475a"
THEME_CATPPUCCIN_MOCHA_SURFACE0="#313244"
THEME_CATPPUCCIN_MOCHA_BASE="#1e1e2e"
THEME_CATPPUCCIN_MOCHA_MANTLE="#181825"
THEME_CATPPUCCIN_MOCHA_CRUST="#11111b"
# Mapping
THEME_CATPPUCCIN_MOCHA_BACKGROUND="${THEME_CATPPUCCIN_MOCHA_BASE}"
THEME_CATPPUCCIN_MOCHA_FOREGROUND="${THEME_CATPPUCCIN_MOCHA_TEXT}"
THEME_CATPPUCCIN_MOCHA_PRIMARY="${THEME_CATPPUCCIN_MOCHA_BLUE}"
THEME_CATPPUCCIN_MOCHA_SECONDARY="${THEME_CATPPUCCIN_MOCHA_LAVENDER}"
THEME_CATPPUCCIN_MOCHA_SUCCESS="${THEME_CATPPUCCIN_MOCHA_GREEN}"
THEME_CATPPUCCIN_MOCHA_DANGER="${THEME_CATPPUCCIN_MOCHA_RED}"
THEME_CATPPUCCIN_MOCHA_WARNING="${THEME_CATPPUCCIN_MOCHA_YELLOW}"
THEME_CATPPUCCIN_MOCHA_INFO="${THEME_CATPPUCCIN_MOCHA_TEAL}"
THEME_CATPPUCCIN_MOCHA_HEADER="${THEME_CATPPUCCIN_MOCHA_MAUVE}"
THEME_CATPPUCCIN_MOCHA_SPINNER="${THEME_CATPPUCCIN_MOCHA_PINK}"
THEME_CATPPUCCIN_MOCHA_ERROR_BACKGROUND="${THEME_CATPPUCCIN_MOCHA_SURFACE0}"
THEME_CATPPUCCIN_MOCHA_ITEM="${THEME_CATPPUCCIN_MOCHA_TEXT}"
THEME_CATPPUCCIN_MOCHA_SELECTED_ITEM="${THEME_CATPPUCCIN_MOCHA_PINK}"


# Function to apply a theme
apply_theme() {
    local theme_name_upper
    theme_name_upper=$(echo "$1" | tr '[:lower:]-' '[:upper:]_') # e.g., catppuccin-latte -> CATPPUCCIN_LATTE

    # Dynamically set general color variables based on the selected theme prefix
    # These are the variables that gum_vars.sh and ui.sh will use
    export BACKGROUND_COLOR=$(eval echo \$THEME_${theme_name_upper}_BACKGROUND)
    export FOREGROUND_COLOR=$(eval echo \$THEME_${theme_name_upper}_FOREGROUND)
    export PRIMARY_COLOR=$(eval echo \$THEME_${theme_name_upper}_PRIMARY)
    export SECONDARY_COLOR=$(eval echo \$THEME_${theme_name_upper}_SECONDARY)
    export SUCCESS_COLOR=$(eval echo \$THEME_${theme_name_upper}_SUCCESS)
    export ERROR_COLOR=$(eval echo \$THEME_${theme_name_upper}_DANGER) # For error text
    export WARNING_COLOR=$(eval echo \$THEME_${theme_name_upper}_WARNING)
    export INFO_COLOR=$(eval echo \$THEME_${theme_name_upper}_INFO)
    export HEADER_COLOR=$(eval echo \$THEME_${theme_name_upper}_HEADER)
    export SPINNER_COLOR=$(eval echo \$THEME_${theme_name_upper}_SPINNER)
    export ERROR_BACKGROUND_COLOR=$(eval echo \$THEME_${theme_name_upper}_ERROR_BACKGROUND)
    export ITEM_COLOR=$(eval echo \$THEME_${theme_name_upper}_ITEM)
    export SELECTED_ITEM_COLOR=$(eval echo \$THEME_${theme_name_upper}_SELECTED_ITEM)

    # Update GUM specific variables that depend on the theme
    # These were previously hardcoded or set with specific color values in gum_vars.sh
    # Now they will use the theme colors.

    export GUM_CHOOSE_CURSOR_FOREGROUND="$PRIMARY_COLOR"
    export GUM_CHOOSE_HEADER_FOREGROUND="$HEADER_COLOR"
    # export GUM_CHOOSE_ITEM_FOREGROUND="$ITEM_COLOR" # gum choose --item.foreground
    # export GUM_CHOOSE_SELECTED_FOREGROUND="$SELECTED_ITEM_COLOR" # gum choose --selected.foreground

    export GUM_CONFIRM_PROMPT_FOREGROUND="$HEADER_COLOR" # Or perhaps WARNING_COLOR
    export GUM_CONFIRM_SELECTED_BACKGROUND="$PRIMARY_COLOR"
    # export GUM_CONFIRM_UNSELECTED_BACKGROUND="$SECONDARY_COLOR" # If needed

    # File picker colors
    export GUM_FILE_CURSOR_FOREGROUND="$PRIMARY_COLOR"
    export GUM_FILE_SYMLINK_FOREGROUND="$INFO_COLOR"
    export GUM_FILE_DIRECTORY_FOREGROUND="$PRIMARY_COLOR" # Often directories are highlighted
    export GUM_FILE_FILE_FOREGROUND="$FOREGROUND_COLOR" # Default text color
    export GUM_FILE_PERMISSIONS_FOREGROUND="$SECONDARY_COLOR"
    export GUM_FILE_SELECTED_FOREGROUND="$SELECTED_ITEM_COLOR"
    export GUM_FILE_FILE_SIZE_FOREGROUND="$SECONDARY_COLOR"
    export GUM_FILE_HEADER_FOREGROUND="$HEADER_COLOR"

    # Pager colors
    export GUM_PAGER_MATCH_FOREGROUND="$PRIMARY_COLOR"
    export GUM_PAGER_MATCH_HIGH_FOREGROUND="$BACKGROUND_COLOR" # Text on high-match background
    export GUM_PAGER_MATCH_HIGH_BACKGROUND="$PRIMARY_COLOR"   # Background for high-match
    # export GUM_PAGER_HELP_FOREGROUND="$SECONDARY_COLOR"
    # export GUM_PAGER_HELP_BACKGROUND="$BACKGROUND_COLOR"

    # Input field colors (placeholders, text, cursor)
    export GUM_INPUT_CURSOR_FOREGROUND="$PRIMARY_COLOR"
    export GUM_INPUT_PLACEHOLDER_FOREGROUND="$SECONDARY_COLOR"
    # export GUM_INPUT_PROMPT_FOREGROUND="$HEADER_COLOR"

    # Style block colors (used by gum style)
    # These are less direct mappings, as gum style sets its own foreground/background.
    # The script mostly uses $BACKGROUND_COLOR, $FOREGROUND_COLOR, etc. directly in gum style commands.

    # Spin (spinner) colors
    export GUM_SPIN_SPINNER_FOREGROUND="$SPINNER_COLOR"
    # export GUM_SPIN_TITLE_FOREGROUND="$FOREGROUND_COLOR" # if title needs theming

    # Write (textarea) colors
    export GUM_WRITE_CURSOR_FOREGROUND="$PRIMARY_COLOR"
    # export GUM_WRITE_PLACEHOLDER_FOREGROUND="$SECONDARY_COLOR"
    # export GUM_WRITE_LINE_NUMBER_FOREGROUND="$SECONDARY_COLOR"
    # export GUM_WRITE_PROMPT_FOREGROUND="$HEADER_COLOR"

    # Glow specific environment variables if needed (though glow has its own style detection)
    # export GLOW_DEFAULT_STYLE=... (can be 'light', 'dark', or a specific .json style file)
    # For now, let glow auto-detect or use its default.
    # If we want to force glow's style based on our theme:
    if [[ "$theme_name_upper" == "LIGHT" || "$theme_name_upper" == "CATPPUCCIN_LATTE" ]]; then
        export GLOW_STYLE="light"
    else
        export GLOW_STYLE="dark" # Most other themes are dark
        # For Dracula, specifically:
        # if [[ "$theme_name_upper" == "DRACULA" ]]; then
        #   export GLOW_STYLE="dracula" # if a dracula.json style is available for glow
        # fi
    fi


    # This is a good place to also set any other global style variables
    # that ui.sh or GeminiSH.sh might use directly.
    # For example, if there were MAIN_COLOR, ACCENT_COLOR, etc.
}

# Default theme if not set
GEMINI_SH_CURRENT_THEME="${GEMINI_SH_CURRENT_THEME:-Catppuccin-Mocha}" # Default to Catppuccin Mocha
apply_theme "$GEMINI_SH_CURRENT_THEME"

# To save the theme choice, you could write GEMINI_SH_CURRENT_THEME to a file, e.g.
# echo "export GEMINI_SH_CURRENT_THEME=\"$GEMINI_SH_CURRENT_THEME\"" > ~/.geminish_theme_config
# And then source this file in GeminiSH.sh or at the beginning of this script.
# For now, it's session-based or can be overridden by environment variable.

true # Ensure the script exits with success when sourced
